version: 2

plan:
  project-key: TBS
  key: ZTSCAN
  name: ZeroThreatAI Scan Plan
  
stages:
  - Setup Project:
      jobs:
        - Fetch project
  - Build Project:
      jobs:
        - Dependency install and build project
  - ZT Vulnerability Scan:
      jobs:
        - Scan Web Application

Fetch project:
  tasks:
    - checkout:
        description: "Checkout Default Repository"
        
Dependency install and build project:
  tasks:
    - script:
      - npm install
    - script:
      - npm run build

Scan Web Application:
  tasks:
    - any-task:
        plugin-key: "com.zerothreatai.plugins.zt-bamboo-plugin:zt-vulnerability-scan-task"
        configuration:
          deploymentUrl: "https://example.com/my-app"

            
            
