version: 2

plan:
  project-key: TEST
  key: ZTSCAN
  name: "ZeroThreatAI Scan Plan"

stages:
  - "Build and Scan":
      jobs:
        - "Default Job":
            key: JOB1
            tasks:
              - checkout:
                  description: "Checkout Default Repository"

              - npm:
                  description: "Install Deps"
                  command: "install"

              - npm:
                  description: "Build NextJS Project"
                  command: "run build"

              - custom:
                  plugin-key: "com.zerothreatai.plugins.zt-bamboo-plugin:zt-vulnerability-scan-task"
                  configuration:
                    deploymentUrl: "https://example.com/my-app"
