version: 2

plan:
  project-key: TBS
  key: ZTSCAN
  name: "ZeroThreatAI Scan Plan"
  
stages:
  - Setup Project
      jobs:
        - Fetch project
  - Build Project
      jobs:
        - Dependency install & build project
  - ZT Vulnerability Scan
      jobs:
        - Scan Web Application

Fetch project:
  tasks:
    - checkout:
        description: "Checkout Default Repository"
        
Dependency install & build project:
  tasks:
    - npm:
        description: "Install Deps"
        command: "install"
    - npm:
        description: "Build NextJS Project"
        command: "run build"

Scan Web Application:
  tasks:
    - custom:
        plugin-key: "com.zerothreatai.plugins.zt-bamboo-plugin:zt-vulnerability-scan-task"
        configuration:
          deploymentUrl: "https://example.com/my-app"

            
            
