version: 2

plan:
  project-key: TEST
  key: ZTSCAN
  name: "ZeroThreatAI Scan Plan"

stages:
  - stage: "Build and Scan"
    jobs:
      - job: "Default Job"
        key: JOB1
        tasks:
          - checkout: # built-in checkout task
              description: "Checkout Default Repository"

          # NPM task
          - npm:
              description: "Install Deps"
              command: "install"
              
          - npm:
              description: "Build NextJS Project"
              command: "run build"

          # ZT Custom Plugin Task
          - custom:
              plugin-key: "com.zerothreatai.plugins.zt-bamboo-plugin:zt-vulnerability-scan-task"
              configuration:
                # The 'deploymentUrl' key must match the name in your configurator
                deploymentUrl: "https://example.com/my-app"
