name: Vulnerability Scan Action

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]
    
permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Custom Action for Vulnerability Scan
      uses: jeelgajera/test-gh-action@main
      with:
        deployment_url: 'https://test-apirepo-action.vercel.app/'
        github_token: ${{ secrets.GITHUB_TOKEN }}
